export const SET_FIRST_CLIENT = 'SET_FIRST_CLIENT';

export const SET_CLIENT_ADDED = 'SET_CLIENT_ADDED';

export const SET_FIRST_PROJECT = 'SET_FIRST_PROJECT';

export const SET_FIRST_BRIEF = 'SET_FIRST_BRIEF';

export const SET_CLIENT_REST = 'SET_CLIENT_REST';

export const SET_PROJECT_REST = 'SET_PROJECT_REST';

export const SET_EPIC_REST = 'SET_EPIC_REST';

export const SET_BRIEF_REST = 'SET_CLIENT_REST';

export const SET_FEATURE_REST = 'SET_FEATURE_REST';

export const SET_SCENARIO_REST = 'SET_SCENARIO_REST';

export const SET_DASHBOARD_CLIENT = 'SET_DASHBOARD_CLIENT';

export const SET_DASHBOARD_PROJECT = 'SET_DASHBOARD_PROJECT';

export const SET_DASHBOARD_BRIEF = 'SET_DASHBOARD_BRIEF';

export const SET_DASHBOARD_FEATURE = 'SET_DASHBOARD_FEATURE';

export const SET_DASHBOARD_SCENARIO = 'SET_DASHBOARD_SCENARIO';

export const SET_INITIAL_CLIENT = 'SET_INITIAL_CLIENT';

export const SET_ALL_CLIENTS = 'SET_ALL_CLIENTS';

export const SET_ALL_PROJECTS = 'SET_ALL_PROJECTS';

export const SET_ALL_BRIEFS = 'SET_ALL_BRIEFS';

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER';

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';

export const SET_ERRORS = 'SET_ERRORS';
